[package]
name = "voronoi_display"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.1"
delaunator = "1.0.2"
plotters = "0.3.5"
rand = "0.8.5"
voronoice = "0.2.0"
